### ISSUE TITLE
tictoc timer

### ISSUE THREAD

**Issue by DLWoodruff** [Pyomo/mpi-sppy#19]
In preparation for Pyomo 6, we need to write our own timer. For one thing, we need to be able to have it go silent.

**Comment by jsiirola** [comment]
@DLWoodruff: I am confused: the TicTocTimer is not going away - Pyomo will have an implementation that is nearly a clone of the one currently in PyUtilib.  (We are doing this so that Pyomo can drop the dependency on pyutilib, not to break things).  Would it be easier to add any features that you need that aren't there now into the Pyomo implementation?

**Comment by bknueven** [comment]
Basically, I don't think we need something as heavy. We just want to:
1. Print time since import with a message for reporting progress
1. Have a flag, or some other easy way, for the user to silence the log.

The move of TicTocTimer seems like a good time to figure out if we should be doing something else.

**Comment by jsiirola** [comment]
FWIW, the following will do exactly that:
```python
from pyomo.common.timing import TicTicTimer
if silence_log:
    importTimer = TicTocTimer(ostream=None)
else:
    importTimer = TicTocTimer()

#....
# Then any time you need time since this module was imported:
importTimer.toc("custom message", delta=False)
```

If you want to be able to silence the log after you have created the timer, we could make the `_ostream` and `_logger` instance attributes officially public and you could set them to None (or to the appropriate file-like object / logger)

**Comment by bknueven** [comment]
We should import `TicTocTimer` from Pyomo, at minimum to eliminate a dependency.
